### ISSUE TITLE
Move GND pad's to ease cables mounting

### ISSUE THREAD

**Issue by gabrielbrunheira** [cnpem-elt/ldc-front-connector-hw#1]
Commit: f648fd1

I suggest moving the GND pad's below the other ones, to facilitate instalation of the two related cables, as shown below:

<img src="https://user-images.githubusercontent.com/16702368/140991370-fa6cfbef-a217-4084-b30d-71b6285ec8d5.png" width = 50%>

**Comment by rogeriomarcondeli** [comment]
Commit: 949241828aae47a688e3a416506c5aa0b8e0037d

Moved the GND pads to facilitate the assembly of the cables, check if it is correct

![InkedCaptura de tela 2021-11-10 090525_LI](https://user-images.githubusercontent.com/62963315/141110623-7cda4c8a-2740-45b1-b9d4-39590e9fbf1e.jpg)
